---
name: ((deployment_name))

instance_groups:
  - azs:
      - az1
    env:
      bosh:
        ipv6:
          enable: true
        authorized_keys: [((ssh_creds.public_key))]
    instances: 1
    jobs: []
    name: bosh
    networks:
      - name: default
    stemcell: stemcell
    vm_type: default

releases: []

stemcells:
  - alias: stemcell
    os: ((stemcell_os))
    version: latest

update:
  canaries: 0
  canary_watch_time: 60000
  max_in_flight: 2
  update_watch_time: 60000

variables:
  - name: ssh_creds
    type: ssh
