---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: bosh/agent
    tag: latest

inputs:
- name: agent-info
- name: bosh-agent

params:
  BOSH_CA_CERT:
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_DEPLOYMENT:
  BOSH_ENVIRONMENT:
  JUMPBOX_PRIVATE_KEY:
  JUMPBOX_USERNAME:
  JUMPBOX_IP:
  GOOS: linux

run:
  path: bosh-agent/ci/tasks/test-integration.sh

